# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class All < Formula
  desc "Filesystem CLI Tools"
  homepage ""
  version "1.15.7"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/kamackay/all/releases/download/v1.15.7/all_Darwin_x86_64.tar.gz"
      sha256 "fbe73f733cfe994ba59d3092f75ac72a748c1965957ea34f33b9e4b2d8499dff"

      def install
        bin.install "all"
      end
    end
    on_arm do
      url "https://github.com/kamackay/all/releases/download/v1.15.7/all_Darwin_arm64.tar.gz"
      sha256 "4f3559faaab6ac69a80d09aa852586fbc70cfa9846c2bafadbe563b4d9df1ec5"

      def install
        bin.install "all"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kamackay/all/releases/download/v1.15.7/all_Linux_x86_64.tar.gz"
        sha256 "69ced713ca8258c9a0a8ccd2ec66f5b67d7e362257a415ea3b5996bc19157797"

        def install
          bin.install "all"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kamackay/all/releases/download/v1.15.7/all_Linux_arm64.tar.gz"
        sha256 "6b244e5deb9610538678d06dc4de16beac31e30a442833db53d92f567bb0e0f7"

        def install
          bin.install "all"
        end
      end
    end
  end
end
