# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class All < Formula
  desc "Filesystem CLI Tools"
  homepage ""
  version "1.11.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kamackay/all/releases/download/v1.11.4/all_1.11.4_Darwin_x86_64.tar.gz"
      sha256 "f3b66a6e237c6c93ff1210848fcc46fd6c645ca8e3c4e3a9a8c5474b4b2f9df2"

      def install
        bin.install "all"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kamackay/all/releases/download/v1.11.4/all_1.11.4_Darwin_arm64.tar.gz"
      sha256 "0f7ee96e9c39ec4dcf632ddaa42e0cc17ba8c1dabc2996332573edf26ec72844"

      def install
        bin.install "all"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kamackay/all/releases/download/v1.11.4/all_1.11.4_Linux_x86_64.tar.gz"
      sha256 "46a3bc1da9417366ce1eff047ea38c13b9198888addb3525bc9e41222ee1ece8"

      def install
        bin.install "all"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kamackay/all/releases/download/v1.11.4/all_1.11.4_Linux_arm64.tar.gz"
      sha256 "085c735311519210f4800621ff82cd7c6ce9166c1c54912cac0cb4ae4d77c9d8"

      def install
        bin.install "all"
      end
    end
  end
end
