# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Thru < Formula
  desc "CLI throughput tools"
  homepage ""
  version "1.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kamackay/thru/releases/download/v1.1.2/thru_1.1.2_Darwin_x86_64.tar.gz"
      sha256 "7be80c5de5d7707127a1384a9ebf3cd7cc418e10ec5ecafe25070b7062e78ac4"

      def install
        bin.install "thru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kamackay/thru/releases/download/v1.1.2/thru_1.1.2_Darwin_arm64.tar.gz"
      sha256 "b6f1b7faef487ea921a358c61ba89ecb89823fee3a4d412030c27e610779d434"

      def install
        bin.install "thru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kamackay/thru/releases/download/v1.1.2/thru_1.1.2_Linux_x86_64.tar.gz"
      sha256 "d13ccb7c7a86e678177390fd36d1877bb956984779c81c7c38c637613722b409"

      def install
        bin.install "thru"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kamackay/thru/releases/download/v1.1.2/thru_1.1.2_Linux_arm64.tar.gz"
      sha256 "d0db7754c0a8732e65bc14b306e161b0c46466656d9762f564445cba9bd3c03a"

      def install
        bin.install "thru"
      end
    end
  end
end
