# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Thru < Formula
  desc "CLI throughput tools"
  homepage ""
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kamackay/thru/releases/download/v1.0.2/thru_1.0.2_Darwin_x86_64.tar.gz"
      sha256 "332ce9ac095959cf0161f87bcf9620cc3fdd465ece44ecee04211a6a0f6aa5e8"

      def install
        bin.install "thru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kamackay/thru/releases/download/v1.0.2/thru_1.0.2_Darwin_arm64.tar.gz"
      sha256 "b9c42499173a45ddf268f25503bf802fa6e118ac73afba848032a0437cea80cc"

      def install
        bin.install "thru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kamackay/thru/releases/download/v1.0.2/thru_1.0.2_Linux_arm64.tar.gz"
      sha256 "b5ee3a0b7c6d75aca173057ca7f1e4f7b09e6d7ff0357c3debd8f80b69b4ba44"

      def install
        bin.install "thru"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kamackay/thru/releases/download/v1.0.2/thru_1.0.2_Linux_x86_64.tar.gz"
      sha256 "c1435c1997b94944cba3af128ff723445e1c23facd8ef470405ede50fad88669"

      def install
        bin.install "thru"
      end
    end
  end
end
