# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TtDelink < Formula
  desc "CLI Tool to remove tracking from a TikTok link"
  homepage ""
  version "1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kamackay/tt-delink/releases/download/v1.0/tt-delink_1.0_Darwin_x86_64.tar.gz"
      sha256 "f298161e8814ae8f30e5e248e64ce47bd47e11d32f592b8dcbddf038136ec0c1"

      def install
        bin.install "tt-delink"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kamackay/tt-delink/releases/download/v1.0/tt-delink_1.0_Darwin_arm64.tar.gz"
      sha256 "bbd45f16c8c70ac53119f26a51575648f97c8ff41271983d43c819b2eca64122"

      def install
        bin.install "tt-delink"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kamackay/tt-delink/releases/download/v1.0/tt-delink_1.0_Linux_x86_64.tar.gz"
      sha256 "cfcaf662b2802204c5d2e972118b7a9eef201517890501e53157180a4048e86d"

      def install
        bin.install "tt-delink"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kamackay/tt-delink/releases/download/v1.0/tt-delink_1.0_Linux_arm64.tar.gz"
      sha256 "35fd9fc4153fbe8e56a7931868fccc914d2e382457c7a4d00cf9649fe90b6bdb"

      def install
        bin.install "tt-delink"
      end
    end
  end
end
